name: Deploy .NET Core API

on:
  workflow_dispatch:
  push:
    branches: [grupo12]

env:
  AZURE_WEBAPP_NAME: helper-api-dotnet-o5
  AZURE_WEBAPP_PACKAGE_PATH: "helper-api-dotnet-o5"
  DOTNET_VERSION: "7.0.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet build --configuration Release ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet publish -c Release --property:PublishDir='../app' ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Deploy to Azure Web apps
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "app"
